### ISSUE TITLE
expose verify-price function (w/o updating store)

### ISSUE THREAD

**Issue by jakob-btc** [hirosystems/stacks-pyth-bridge#30]
The current `pyth-oracle` contract only exposes a `verify-and-update-price` which verifies the data package and then also updates the `store`. 

This can lead to issues with our contracts because we need price data for one specific timestamp in order to settle our contracts (the timestamp corresponding to our option expiry). 

I've made a call to `pyth-helper` with data from the past and the `verify-and-update-price` function failed with `err u5003`. (See: https://explorer.hiro.so/txid/0x63f384b78c1f08d24a6ab22cfc56885c85f6638843d9ae54a1eb4477c86c4596?chain=testnet)

The error is comes up because the oracle tries to update the `pyth-store` contract with the price data submitted, which fails because there's newer data already in the store.

This is a problem for us because we might run into a situation where we want to verify a specific oracle data package but we receive an error if the price is in the past / a newer data package exists in the store.

The remedy is pretty straight forward: We need a `verify-price` function that only verifies that the data is indeed from a Pyth oracle but does not try to update the `pyth-store`.

Essentially a function in `pyth-oracle` that removes this contract-call:

` (updated-prices (try! (contract-call? pyth-storage-contract write decoded-prices)))`

**Comment by lgalabru** [comment]
Thanks for opening this issue @gandalf77. This feature request is being addressed in https://github.com/hirosystems/stacks-pyth-bridge/pull/31.
