### ISSUE TITLE
Update calls will fail if the update is not recent or if there is a newer update

### ISSUE THREAD

**Issue by ali-bahjati** [hirosystems/stacks-pyth-bridge#35]
This is not the behaviour in other contracts. I think it is fine as long as it doesn't revert the entire transaction. @lgalabru do you confirm that people can catch and handle the outcome of the contract call?

**Comment by lgalabru** [comment]
The write contract call errors if the PNAU ends up not being written.
This is an error that developers can use with some control flow, not a panic / revert aborting the transaction.

**Comment by lgalabru** [comment]
The intention there was to be maximize the number of options on the table.
Depending on the use case, developers can either cascade the error and abort, or swallow the error and read the latest price.

**Comment by ali-bahjati** [comment]
Makes sense. Thanks for explaining!
